import {
  AlertTriangle,
  ArrowRight,
  ArrowUpDown,
  BarChart,
  Bell,
  Check,
  ChevronLeft,
  ChevronRight,
  CircleSlash,
  CreditCard,
  DollarSign,
  Edit,
  Eye,
  EyeOff,
  File,
  FileText,
  Heart,
  HelpCircle,
  Home,
  Image,
  Laptop,
  LayoutDashboard,
  Loader2,
  LogOut,
  Menu,
  MessageSquare,
  Moon,
  MoreVertical,
  Package,
  Plus,
  Search,
  Settings,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Star,
  Store,
  SunMedium,
  Timer,
  Trash,
  Twitter,
  Upload,
  User,
  Video,
  Watch,
  X,
  type LucideIcon,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Store,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  menu: Menu,
  settings: Settings,
  upload: Upload,
  credit: CreditCard,
  help: HelpCircle,
  user: User,
  arrowRight: ArrowRight,
  edit: Edit,
  eye: Eye,
  eyeOff: EyeOff,
  check: Check,
  warning: AlertTriangle,
  error: CircleSlash,
  file: File,
  fileText: FileText,
  plus: Plus,
  image: Image,
  laptop: Laptop,
  moon: Moon,
  sun: SunMedium,
  cart: ShoppingCart,
  twitter: Twitter,
  more: MoreVertical,
  sorting: ArrowUpDown,
  store: Store,
  logout: LogOut,
  dashboard: LayoutDashboard,
  product: Package,
  order: ShoppingCart,
  star: Star,
  shirt: Shirt,
  clock: Timer,
  home: Home,
  smartphone: Smartphone,
  bag: ShoppingBag,
  watch: Watch,
  heart: Heart,
  video: Video,
  messageSquare: MessageSquare,
  dollar: DollarSign,
  search: Search,
  notification: Bell,
  chart: BarChart
}
